// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	model "ToDo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockService) AddUser(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockServiceMockRecorder) AddUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockService)(nil).AddUser), user)
}

// ChangeTaskCondition mocks base method.
func (m *MockService) ChangeTaskCondition(id, login string, isDone bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeTaskCondition", id, login, isDone)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeTaskCondition indicates an expected call of ChangeTaskCondition.
func (mr *MockServiceMockRecorder) ChangeTaskCondition(id, login, isDone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeTaskCondition", reflect.TypeOf((*MockService)(nil).ChangeTaskCondition), id, login, isDone)
}

// CreateTask mocks base method.
func (m *MockService) CreateTask(task *model.Task, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", task, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockServiceMockRecorder) CreateTask(task, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockService)(nil).CreateTask), task, login)
}

// DeleteTask mocks base method.
func (m *MockService) DeleteTask(id, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", id, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockServiceMockRecorder) DeleteTask(id, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockService)(nil).DeleteTask), id, login)
}

// GetAllTasks mocks base method.
func (m *MockService) GetAllTasks(login string) ([]model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", login)
	ret0, _ := ret[0].([]model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockServiceMockRecorder) GetAllTasks(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockService)(nil).GetAllTasks), login)
}

// LookUpReqUser mocks base method.
func (m *MockService) LookUpReqUser(user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookUpReqUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// LookUpReqUser indicates an expected call of LookUpReqUser.
func (mr *MockServiceMockRecorder) LookUpReqUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookUpReqUser", reflect.TypeOf((*MockService)(nil).LookUpReqUser), user)
}
